export 'api_utils/api_client.dart';
export 'api_utils/api_failure.dart';
export 'api_utils/api_response_model.dart';
export 'api_utils/auth_interceptor.dart';
export 'config/app_config.dart';
export 'config/countries.dart';
export 'config/flavor_config.dart';
export 'config/env_loader.dart';
export 'locator/locator_service.dart';
export 'navigator/app_router.dart';
export 'network/network_status_provider.dart';
export 'secure_storage/secure_storage_service.dart';
export 'utils/result.dart';
export 'utils/sizing_utils.dart';
export 'utils/extensions.dart';
export 'utils/validators.dart';
export 'utils/logger.dart';
export 'theme/app_theme.dart';
export 'theme/app_palette.dart';
export 'theme/app_typography.dart';
export 'widgets/app_button.dart';
export 'widgets/app_text_field.dart';
export 'widgets/app_toast.dart';
export 'widgets/desktop_manager.dart';
export 'mock/mock_credentials.dart';
export 'network/api_endpoints.dart';
export 'network/file_repository.dart';

export 'package:flutter/material.dart';
export 'package:flutter/foundation.dart';
export 'package:flutter/services.dart';
export 'package:flutter_riverpod/flutter_riverpod.dart';
export 'package:flutter_riverpod/legacy.dart';
export 'package:flutter_secure_storage/flutter_secure_storage.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:dio/dio.dart';
export 'package:flutter_dotenv/flutter_dotenv.dart';
export 'package:go_router/go_router.dart';
export 'package:get_it/get_it.dart';
export 'package:flutter_markdown/flutter_markdown.dart';
export 'package:file_picker/file_picker.dart';
export 'package:record/record.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:app_links/app_links.dart';
export 'package:google_sign_in/google_sign_in.dart';
export 'services/google_auth_service.dart';
export 'package:agora_rtc_engine/agora_rtc_engine.dart' hide LogLevel;
export 'package:desktop_drop/desktop_drop.dart';
export 'package:cross_file/cross_file.dart';
export 'package:super_clipboard/super_clipboard.dart';
export 'package:local_notifier/local_notifier.dart';
export 'package:window_manager/window_manager.dart';
export 'package:tray_manager/tray_manager.dart';
// import 'package:zedu/core/services/realtime_service.dart'; // Adjust path if needed

export 'dart:async' hide AsyncError;
export 'dart:convert';
export 'dart:io';
export 'dart:math' hide log, Rectangle;
export 'dart:developer' show log;
export 'package:web_socket_channel/web_socket_channel.dart';
export 'package:audioplayers/audioplayers.dart';
export 'utils/date_formatter.dart';
